---

- name: run mkswap
  command: mkswap /dev/mapper/{{ storage_pools[0].name }}-swap

- name: run swapon
  command: swapon /dev/mapper/{{ storage_pools[0].name }}-swap

- name: set swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ swap_swappiness }}"
    state: present

- name: write swap entry in fstab
  mount:
    path: none
    src: /dev/mapper/{{ storage_pools[0].name }}-swap
    fstype: swap
    opts: sw,nofail
    passno: 0
    dump: 0
    state: present